/* Generated by materialize_syscall_batch.py */
#include <errno.h>
#include <stdio.h>
#include <string.h>
#include <sys/epoll.h>
#include <unistd.h>

int main(void)
{
	errno = 0;
	struct epoll_event ev;
	memset(&ev, 0, sizeof(ev));
	int epfd = epoll_create1(0);
	int r = epoll_ctl(epfd, EPOLL_CTL_ADD, -1, &ev);
	close(epfd);
	int e = errno;
	dprintf(1, "CASE epoll_ctl.badfd ret=%ld errno=%d note=handwritten\n", (long)r, e);
	return 0;
}

