/* Generated by materialize_syscall_batch.py */
#include <errno.h>
#include <stdio.h>
#include <string.h>
#include <sys/epoll.h>
#include <signal.h>
#include <unistd.h>

int main(void)
{
	errno = 0;
	struct epoll_event ev[1];
	memset(ev, 0, sizeof(ev));
	int fd = epoll_create1(0);
	close(fd);
	int r = epoll_pwait(fd, ev, 1, 0, NULL);
	int e = errno;
	dprintf(1, "CASE epoll_pwait.badfd ret=%ld errno=%d note=handwritten\n", (long)r, e);
	return 0;
}

